### PR TITLE
reverse hw

### PR DESCRIPTION
**Pull request by brentxphillips**
comment

### CODE REVIEW

**Comment by tgaff** [comment]
Hi @brentxphillips could you move your file into your directory.  See the instructions here for details: https://github.com/ga-students/bewd_sf_10_homework#how-to-use-this-repo

**Comment by tgaff** [comment]
you don't need to close the pull request to do that, just push a new commit that fixes the problem

**Comment by brentxphillips** [comment]
Hey I'm sorry but the link doesn't provide any useful information.

So as far as I know, I'm under the impression that I've created a pull
request for GA-students master to accept, isn't getting the file the rest
of the way out of my hands and up to the Master's moderator?

What sort of clues should I look for to verify things are on track or not?
What should a beginner know about working in and out of someone else's repo
vs their own in terms of troubleshooting?

b

**Comment by brentxphillips** [comment]
comment

**Pull request closed without merging**
