### PR TITLE
Adding all of my homework!

### PR DESCRIPTION
**Pull request by leahreitz**
Sorry, I've been struggling with the git life.

### CODE REVIEW

**Comment by tgaff** [comment]
uh oh @leahreitz it looks like that .DS_Store is back again.  Could you `git rm .DS_Store` and `git commit -m "remove DS_Store"` ?

**Comment by leahreitz** [comment]
I think I did it?

**Comment by tgaff** [comment]
you did it... but it didn't seem to solve the problem hmmmm  

I'll dig a little deeper.

**Comment by tgaff** [comment]
I see what it is.  You got rid of `LeahReitz-leahreitz/.DS_Store`  but `.DS_Store`  (in the root of the repo) is still there.  You can just go to the root of the repo and `git rm .DS_Store` and commit again.  By the root, I mean the directory above `LeahReitz-leahreitz`.  So if you're in `LeahReitz-leahreitz`, then first `cd ..`

I hope that made sense!  @leahreitz

**Comment by tgaff** [comment]
if that didn't make sense, please get with one of us in office hours or on slack

**Comment by leahreitz** [comment]
Okay, I followed your instructions. Hopefully it's all good (and if not,
I'll find you or another TA before class).

**Pull request merged**
