### PR TITLE
Lesson 11

### PR DESCRIPTION
**Pull request by mikeyferg**

### CODE REVIEW

**Comment by Borgaard** [comment]
Git yer .DS_Store files outta here.

**Comment by mikeyferg** [comment]
how?

**Comment by Borgaard** [comment]
In `bewd_sf_10_homework/MichaelFerguson-mikeyferg/` you've got a hidden file by the name of `.DS_Store`. It's just a bunch of meta data about your app, but it causes conflicts. Do `ls -a` to see it's in your directory, then `rm .DS_Store` before pushing again.

**Comment by Borgaard** [comment]
Also you can pull this repo because `.DS_Store` is in the `.gitignore` file.

**Comment by Borgaard** [comment]
Fancy! Merging.

**Pull request merged**
